---
title: "Bird joins"
author: "Felicia Cruz"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
```


```{r}
bird_observations<- read_csv(here("data", "52_pp52_birds_1.csv"))

sites <- read_csv(here("data", "52_pp52_sites_1.csv"))

surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))

taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))

birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL")) %>% 
  filter(site_id %in% c("LI-W", "NU-C"))
```

### Left join practice 
```{r}
birds_left <- left_join(birds_subset, sites, by = "site_id")

birds_left <- left_join(birds_left, taxalist, by = "species_id")
```

### Full join practice
A full join between `birds_subset` and `sites` should contain
```{r}
birds_full <- full_join(birds_subset, sites, by = "site_id")

```

### Inner join practice
```{r}
birds_inner <- inner_join(birds_subset, taxalist, by = "species_id")

birds_inner_left <- left_join(birds_subset, taxalist, by = "species_id")
```

## Data Wrangling and Visualization with Birds

```{r}
birds <- bird_observations %>% 
  rename(bird_obs_notes = notes)

birds_sub <- birds %>% 
  left_join(taxalist, by = "species_id") %>% 
  left_join(sites, by = "site_id") %>% 
  left_join(surveys, by = c("survey_id", "site_id")) %>% 
  select(survey_date, common_name, park_name, bird_count)

birds_sub <- birds_sub %>% 
  mutate(survey_month = month(survey_date)) %>% 
  mutate(survey_month = as.factor(survey_month)) %>% 
  relocate(survey_month, .after = survey_date)

tot_birds_park_and_month <- birds_sub %>% 
  group_by(park_name, survey_month) %>% 
  summarize(count = n()) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))
```




